import { e, formatTime, icon, localDay } from '../lib/dom.js';
import { pageCard } from '../components/common.js';
import { questionStats } from '../lib/quiz.js';
import { readLink } from '../lib/router.js';
export function renderHome(root, ctx) {
    const { catalog, store } = ctx;
    const learned = catalog.pages.filter(p => store.getPage(p.number).learned).length;
    const viewed = catalog.pages.filter(p => store.getPage(p.number).visits > 0).length;
    const recent = [...store.pages.values()].filter(p => p.lastViewed > 0).sort((a, b) => b.lastViewed - a.lastViewed).slice(0, 4).flatMap(r => { const p = catalog.pages.find(p => p.number === r.page); return p ? [p] : []; });
    const continuePage = recent[0] ?? catalog.pages[0];
    const weak = catalog.questions.filter(q => questionStats(q.id, store.attempts).weak).length;
    const correct = store.attempts.filter(a => a.correct).length;
    const totalSeconds = [...store.days.values()].reduce((n, d) => n + d.seconds, 0);
    root.innerHTML = `<header class="home-heading"><div><p class="eyebrow">TECHNICAL LEARNING WORKSPACE</p><h1>資料を知識に。<br/><span>知識を判断に。</span></h1><p>原理を読み、図で確かめ、現場の問いを解く。<br/>異物解析とフィルム検査を、原文から学ぶワークスペース。</p><div class="button-row"><a class="button primary" href="${readLink(continuePage.number)}">${icon('book', 18)} ${recent.length ? '続きから読む' : '教材を開く'} ${icon('arrow', 18)}</a><a class="button secondary" href="#/quiz">理解度を確かめる</a></div><div class="hero-meta"><span>${icon('lock', 14)} 学習記録はこの端末内に保存</span><span>原本 ${catalog.pages.length}ページ</span><span>演習 ${catalog.questions.length}問</span></div></div><div class="hero-art" aria-hidden="true"><div class="art-orbit orbit-one"></div><div class="art-orbit orbit-two"></div><div class="art-document back"><i></i><i></i><i></i><i></i></div><div class="art-document front"><span class="art-kicker">MATERIAL INSIGHT</span><svg viewBox="0 0 220 105"><path d="M5 85H215M5 15v70"/><polyline points="5,76 25,73 37,65 43,22 48,73 63,72 77,65 82,49 89,69 109,73 118,35 126,72 139,64 149,16 159,69 176,54 182,72 202,69 215,74"/></svg><i></i><i></i><i></i><span class="art-seal">${icon('check', 21)} SOURCE BASED</span></div><span class="art-tag">READ → THINK → APPLY</span></div></header>
 <section class="stats-grid" aria-label="学習の概要"><div class="stat"><span>学習済みページ</span><strong>${learned}<small> / ${catalog.pages.length}</small></strong><progress max="${catalog.pages.length}" value="${learned}"></progress><small>閲覧済み ${viewed}ページ</small></div><div class="stat"><span>演習の正答率</span><strong>${store.attempts.length ? Math.round(correct / store.attempts.length * 100) : '−'}<small> %</small></strong><small>累計 ${store.attempts.length}回の解答</small></div><a class="stat stat-link" href="#/weak"><span>復習待ちの問題 ${icon('arrow', 15)}</span><strong>${weak}<small> 問</small></strong><small>誤答後に2回連続正解で克服</small></a><div class="stat"><span>累計学習時間</span><strong class="time-stat">${formatTime(totalSeconds)}</strong><small>今日 ${formatTime(store.days.get(localDay())?.seconds ?? 0)}</small></div></section>
 <section><div class="section-title"><div><h2>3つの学習テーマ</h2><p>関心のあるテーマから、原文と演習を行き来できます。</p></div><span class="small-label">LEARNING PATHS</span></div><div class="category-grid">${catalog.categories.map((c, i) => { const pages = catalog.pages.filter(p => p.category === c.id); const count = catalog.questions.filter(q => q.category === c.id).length; const done = pages.filter(p => store.getPage(p.number).learned).length; return `<article class="category-card ${c.id}"><div class="category-top"><span class="category-icon">${icon(c.icon, 24)}</span><span>0${i + 1}</span></div><h3>${e(c.title)}</h3><p>${e(c.description)}</p><div class="category-metrics"><span>${pages.length}ページ</span><span>${count}問</span><span>${catalog.figures.filter(f => f.category === c.id).length}図表</span></div><progress max="${pages.length}" value="${done}" aria-label="${e(c.short)}の進捗"></progress><div class="card-footer"><a href="${readLink(pages[0].number)}">教材を読む ${icon('arrow', 17)}</a><a class="text-link muted" href="#/quiz?category=${c.id}">演習へ</a></div></article>`; }).join('')}</div></section>
 <div class="home-bottom"><section class="panel"><div class="section-title compact"><h2>${recent.length ? '最近見たページ' : '学習の入口'}</h2><a href="#/history" class="text-link">学習履歴 ${icon('arrow', 15)}</a></div>${(recent.length ? recent : catalog.pages.filter(p => [40, 285, 294].includes(p.number))).map(p => pageCard(ctx, p)).join('')}</section><section class="panel discovery-panel"><span class="category-icon">${icon('search', 24)}</span><h2>疑問から教材を探す</h2><p>自然な言葉から関連ページ・図表・問題を検索します。回答を作らず、教材の根拠へ案内します。</p><a class="suggestion" href="#/search?q=${encodeURIComponent('フィッシュアイとゲルの違い')}">フィッシュアイとゲルの違い ${icon('arrow', 16)}</a><a class="suggestion" href="#/search?q=${encodeURIComponent('ブリード解析でFTIRを使う理由')}">ブリード解析でFTIRを使う理由 ${icon('arrow', 16)}</a><div class="source-note">p40〜50のEDXは蛍光X線分析装置を指します。SEM-EDXとは励起源が異なります。<a href="${readLink(42)}">p42で確認</a></div></section></div>`;
}
