import { e, icon, qs, formatDate } from '../lib/dom.js';
import { questionStats, typeLabels } from '../lib/quiz.js';
import { heading, categoryOptions, emptyState } from '../components/common.js';
import { accuracyTrend } from '../components/trend.js';
import { readLink } from '../lib/router.js';
export function renderWeak(root, ctx) {
    root.innerHTML = heading('REVIEW & RETAIN', '苦手問題モード', '誤答は履歴に残ります。誤答後の2回連続正解を「克服」の目安にします。') + `<div class="filter-bar"><select id="weak-category" aria-label="苦手問題カテゴリ">${categoryOptions(ctx)}</select><select id="weak-status" aria-label="復習状態"><option value="active">復習待ち</option><option value="all">過去に間違えた全問題</option><option value="mastered">克服した問題</option></select><span class="small muted" id="weak-count"></span></div><div id="weak-results"></div>`;
    function update() { const category = qs('#weak-category', root).value; const status = qs('#weak-status', root).value; const items = ctx.catalog.questions.map(q => ({ q, s: questionStats(q.id, ctx.store.attempts) })).filter(({ q, s }) => (!category || q.category === category) && s.wrong > 0 && (status === 'all' || (status === 'mastered' ? s.mastered : s.weak))).sort((a, b) => a.s.correct / a.s.total - b.s.correct / b.s.total || b.s.last - a.s.last); qs('#weak-count', root).textContent = `${items.length}問`; qs('#weak-results', root).innerHTML = items.length ? items.map(({ q, s }) => `<article class="panel weak-card"><div class="weak-heading"><div class="tags"><span class="badge">${typeLabels[q.type]}</span><span class="badge ${s.mastered ? 'success' : 'warning'}">${s.mastered ? '克服' : '復習待ち'}</span><span class="small muted">${s.correct} / ${s.total}回正解 · 直近${s.streak}回連続正解</span></div><span class="small muted">${formatDate(s.last)}</span></div><h2>${e(q.prompt)}</h2><div class="weak-bottom"><div class="weak-sources">${q.sources.map(s => `<a class="text-link" href="${readLink(s.page, s.section)}">p${s.page}の根拠</a>`).join('')}<p class="small muted">${s.due <= Date.now() ? '復習目安：今日' : '次の復習目安：' + formatDate(s.due)}。間隔は学習支援用の目安です。</p></div>${accuracyTrend(s.rows, 'この問題の正答率推移')}<a class="button primary" href="#/quiz?question=${encodeURIComponent(q.id)}">再挑戦 ${icon('arrow', 16)}</a></div><details class="attempt-details"><summary>解答履歴を確認</summary><div class="table-wrap"><table><thead><tr><th>日時</th><th>結果</th><th>選択した解答</th></tr></thead><tbody>${s.rows.map(a => `<tr><td>${formatDate(a.at)}</td><td>${a.correct ? '正解' : '不正解'}</td><td>${e(q.choices.find(c => c.id === a.choiceId)?.text ?? '')}</td></tr>`).join('')}</tbody></table></div></details></article>`).join('') : emptyState('この条件の苦手問題はありません', '演習で間違えた問題が自動的に記録されます。', '<a class="button primary" href="#/quiz">演習を始める</a>'); }
    qs('#weak-category', root).addEventListener('change', update);
    qs('#weak-status', root).addEventListener('change', update);
    update();
}
